const cloudinaryAPI = process.env.CLOUDINARY_BASE_URL;


exports.seed = async function(knex) {
  await knex('songs').del();

  await knex('songs').insert([
    { 
        id: 1,
        title: "Leap Of Faith",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067056/Leap_Of_Faith_xdphbg.mp3`,
        type: "album",
        duration: 60,
        averageColor: "#677effff",
    },
    {         
        id: 2,
        title: "Drawing New Worlds",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067198/Drawing_New_Worlds_euhoh5.mp3`,
        type: "album",
        duration: 282,
        averageColor: "#677effff",
    },
    {
        id: 3,
        title: "Doctrine Of The Wicked",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067161/Doctrine_Of_The_Wicked_uo3tue.mp3`,
        type: "album",
        duration: 278,
        averageColor: "#677effff",
    },
    {
        id: 4,
        title: "Anthem",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067136/Anthem_iudthg.mp3`,
        type: "album",
        duration: 264,
        averageColor: "#677effff",
    },
    {
        id: 5,
        title: "Fragile Madness",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067207/Fragile_Madness_qwplat.mp3`,
        type: "album",
        duration: 310,
        averageColor: "#677effff",
    },
    {
        id: 6,
        title: "Shadows Surround Me",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067291/Shadows_Surround_Me_aycusn.mp3`,
        type: "album",
        duration: 337,
        averageColor: "#677effff",
    },
    {
        id: 7,
        title: "Sorrowful Cries",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067134/Sorrowful_Cries_teccmp.mp3`,
        type: "album",
        duration: 251,
        averageColor: "#677effff",
    },
    {
        id: 8,
        title: "Unfeind Emotions",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067129/Unfeind_Emotions_akkelb.mp3`,
        type: "album",
        duration: 267,
        averageColor: "#677effff",
    },
    {
        id: 9,
        title: "Cosmic Balance",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067327/Cosmic_Balance_ggb9rx.mp3`,
        type: "album",
        duration: 374,
        averageColor: "#677effff",
    },
    {
        id: 10,
        title: "Shattered Light",
        artist: "Neperia",
        album: "Drawing New Worlds",
        year: 2018,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Drawing_New_Worlds_txdwf8.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067324/Shattered_Light_ynloah.mp3`,
        type: "album",
        duration: 351,
        averageColor: "#677effff",
    },
    {
        id: 11,
        title: "Domino",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067065/Domino_ycqyfi.mp3`,
        type: "album",
        duration: 103,
        averageColor: "#ffe99bff",
    },
    {
        id: 12,
        title: "iΔÆA",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067212/i%CE%94%C3%86A_bqg6qs.mp3`,
        type: "album",
        duration: 287,
        averageColor: "#ffe99bff",
    },
    {
        id: 13,
        title: "I, Liar",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067332/I_Liar_o9zpvl.mp3`,
        type: "album",
        duration: 343,
        averageColor: "#ffe99bff",
    },
    {
        id: 14,
        title: "Like A Broken Toy",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067389/Like_A_Broken_Toy_yrwyly.mp3`,
        type: "album",
        duration: 379,
        averageColor: "#ffe99bff",
    },
    {
        id: 15,
        title: "The Maze",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067223/The_Maze_xrms3o.mp3`,
        type: "album",
        duration: 294,
        averageColor: "#ffe99bff",
    },
    {
        id: 16,
        title: "Breath",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067110/Breath_wzfvyx.mp3`,
        type: "album",
        duration: 232,
        averageColor: "#ffe99bff",
    },
    {
        id: 17,
        title: "Contrast",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067291/Contrast_uuxtix.mp3`,
        type: "album",
        duration: 332,
        averageColor: "#ffe99bff",

    },
    {
        id: 18,
        title: "The Story Is Told",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067375/The_Story_Is_Told_xhhfv8.mp3`,
        type: "album",
        duration: 328,
        averageColor: "#ffe99bff",
    },
    {
        id: 19,
        title: "Funeral Pyre",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067366/Funeral_Pyre_dt8dfl.mp3`,
        type: "album",
        duration: 351,
        averageColor: "#ffe99bff",
    },
    {
        id: 20,
        title: "Einstellung",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067302/Einstellung_mu4bip.mp3`,
        type: "album",
        duration: 341,
        averageColor: "#ffe99bff",
    },
    {
        id: 21,
        title: "Ptesmata",
        artist: "Neperia",
        album: "Ptesmata",
        year: 2022,
        image: `${cloudinaryAPI}/image/upload/v1761067160/Ptesmata_kotxaa.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067365/Ptesmata_fdyphr.mp3`,
        type: "album",
        duration: 364,
        averageColor: "#ffe99bff",
    },
    {
        id: 22,
        title: "Scaling The Summit (feat. Gogo Melone)",
        artist: "Neperia",
        album: "Scaling The Summit",
        year: 2023,
        image: `${cloudinaryAPI}/image/upload/v1761067105/Scaling_The_Summit_gqblvn.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067370/Scaling_The_Summit_feat._Gogo_Melone_mhsgzw.mp3`,
        type: "ep",
        duration: 323,
        averageColor: "#ffceabff",
    },
    {
        id: 23,
        title: "Doctrine Of The Wicked",
        artist: "Neperia",
        album: "Scaling The Summit",
        year: 2023,
        image: `${cloudinaryAPI}/image/upload/v1761067105/Scaling_The_Summit_gqblvn.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067256/Drawing_New_Worlds_fkrgcd.mp3`,
        type: "ep",
        duration: 277,
        averageColor: "#ffceabff",
    },
    {
        id: 24,
        title: "Drawing New Worlds",
        artist: "Neperia",
        album: "Scaling The Summit",
        year: 2023,
        image: `${cloudinaryAPI}/image/upload/v1761067105/Scaling_The_Summit_gqblvn.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067256/Drawing_New_Worlds_fkrgcd.mp3`,
        type: "ep",
        duration: 286,
        averageColor: "#ffd7a2ff",
    },
    {
        id: 25,
        title: "Shattered Light",
        artist: "Neperia",
        album: "Scaling The Summit",
        year: 2023,
        image: `${cloudinaryAPI}/image/upload/v1761067105/Scaling_The_Summit_gqblvn.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067380/Shattered_Light_i3ov7m.mp3`,
        type: "ep",
        duration: 361,
        averageColor: "#ffceabff",
    },
    {
        id: 26,
        title: "Minokawa",
        artist: "Neperia",
        album: "Minokawa",
        year: 2023,
        image: `${cloudinaryAPI}/image/upload/v1761067070/Minokawa_ttz6iv.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067189/Minokawa_kkeibq.mp3`,
        type: "single",
        duration: 284,
        averageColor: "#ffc4afff",
    },
    {
        id: 27,
        title: "Vritra's Garden",
        artist: "Neperia",
        album: "Vritra's Garden",
        year: 2023,
        image: `${cloudinaryAPI}/image/upload/v1761067083/Vritra_s_Garden_lqveiw.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067257/Vritra_s_Garden_dbqgpu.mp3`,
        type: "single",
        duration: 264,
        averageColor: "#d3ffbeff",
    },
    {
        id: 28,
        title: "Happy New Age",
        artist: "Neperia",
        album: "Happy New Age",
        year: 2025,
        image: `${cloudinaryAPI}/image/upload/v1761067096/Happy_New_Age_mrecll.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067154/Happy_New_Age_cku3bu.mp3`,
        type: "single",
        duration: 283,
        averageColor: "#9deeff",
    },
    {
        id: 29,
        title: "Zenaida's Voice",
        artist: "Neperia",
        album: "Zenaida's Voice",
        year: 2025,
        image: `${cloudinaryAPI}/image/upload/v1761067085/Zenaida_s_Voice_tizck3.jpg`,
        url: `${cloudinaryAPI}/video/upload/v1761067250/Zenaida_s_Voice_aeuc5c.mp3`,
        type: "single",
        duration: 293,
        averageColor: "#7cbab0ff",
    },
  ]);
};


